// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/rongrong/Documents/2024学习代码/ReactHooks/node_modules/.pnpm/dumi@2.4.14_@babel+core@7.26.0_@types+node@22.10.1_eslint@7.2.0_jest@29.4.1_prettier@2.8.8_re_ftvsxpq5pa5z4pbat3mbtjiu5q/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
