// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/rongrong/Documents/2024学习代码/ReactHooks/node_modules/.pnpm/dumi@2.4.14_@babel+core@7.26.0_@types+react@19.0.0_dfm7ki5fyxpdrenxkeyndrqepy/node_modules/dumi/theme-default/slots/Content/index.js';
