// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/rongrong/Documents/2024学习代码/ReactHooks/node_modules/.pnpm/dumi@2.4.14_@babel+core@7.26.0_@types+node@22.10.1_@types+react@19.0.0_eslint@7.2.0_jest@29.4_iqbwl5u7w3sxpwrp7d7hj6qu4q/node_modules/dumi/theme-default/slots/ColorSwitch/index.js';
